### ISSUE TITLE
这个多线程下会不会转发不过来

### ISSUE THREAD

**Issue by unikcc** [captain686/proxy_pool-with-openresty#1]
+ 假设我用**10**台机器，每台机器**10**个进程进行爬虫，都通过这个隧道代理来转发请求，没有sleep，会不会出现CPU（8核）满载，转发不过来

**Comment by captain686** [comment]
这个问题更大程度上是取决于redis连接池上的限制，但是我也没有去进行过如此高强度的测试，所以实在抱歉这个问题我没办法给你一个确切的答案

**Comment by captain686** [comment]
如果真的有这么大的需求可以考虑做redis的集群，但是这样的话可能就需要修改proxy_pool的代码了

**Comment by unikcc** [comment]
好的，谢谢，我先试下吧；想快速爬大量数据
