### ISSUE TITLE
nginx_lua连接redis非0库

### ISSUE THREAD

**Issue by Flat-Chen** [captain686/proxy_pool-with-openresty#2]
大佬，请问一下如果proxy_ip存放的位置不是redis的0号库，配置文件里设置redis连接信息的时候如何指定redis连接的库呢，感谢感谢

**Comment by captain686** [comment]
> 大佬，请问一下如果proxy_ip存放的位置不是redis的0号库，配置文件里设置redis连接信息的时候如何指定redis连接的库呢，感谢感谢

在[nginx.conf#L46](https://github.com/captain686/proxy_pool-with-openresty/blob/main/nginx.conf#L46)后面使用
```lua
local ok, err = red:select(1)
if not ok then
     ngx.log(nginx.ERR, "failed to select: ", err)
     return
end
```
更换数据库

**Comment by Flat-Chen** [comment]
感谢大佬，已解决
