### ISSUE TITLE
出现超时

### ISSUE THREAD

**Issue by sunxhap** [captain686/proxy_pool-with-openresty#4]
大佬帮忙看下如下报错

2024/11/11 12:03:02 [error] 57234#57234: *456425 recv() failed (104: Connection reset by peer) while proxying and reading from upstream, client: 172.18.131.12, server: 0.0.0.0:9976, upstream: "110.199.204", bytes from/to client:1717/46483, bytes from/to upstream:46483/1717
2024/11/11 12:03:02 [error] 57232#57232: *459112 upstream timed out (110: Connection timed out) while connecting to upstream, client: 172.18.131.12, server: 0.0.0.0:9976, upstream: "123.77.2", bytes from/to client:0/0, bytes from/to upstream:0/0

**Comment by captain686** [comment]
> 大佬帮忙看下如下报错
> 
> 2024/11/11 12:03:02 [error] 57234#57234: *456425 recv() failed (104: Connection reset by peer) while proxying and reading from upstream, client: 172.18.131.12, server: 0.0.0.0:9976, upstream: "110.199.204", bytes from/to client:1717/46483, bytes from/to upstream:46483/1717 2024/11/11 12:03:02 [error] 57232#57232: *459112 upstream timed out (110: Connection timed out) while connecting to upstream, client: 172.18.131.12, server: 0.0.0.0:9976, upstream: "123.77.2", bytes from/to client:0/0, bytes from/to upstream:0/0

`upstream: "123.77.2"`上游代理ip不对
